# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pairwise_categorical.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(953, 595)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.listWidgetAllColumns = QtWidgets.QListWidget(self.frame)
        self.listWidgetAllColumns.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.listWidgetAllColumns.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidgetAllColumns.setObjectName("listWidgetAllColumns")
        self.verticalLayout.addWidget(self.listWidgetAllColumns)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonAddCat = QtWidgets.QPushButton(self.frame)
        self.pushButtonAddCat.setObjectName("pushButtonAddCat")
        self.horizontalLayout_2.addWidget(self.pushButtonAddCat)
        self.pushButtonAddNum = QtWidgets.QPushButton(self.frame)
        self.pushButtonAddNum.setObjectName("pushButtonAddNum")
        self.horizontalLayout_2.addWidget(self.pushButtonAddNum)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelCategoricalName = QtWidgets.QLabel(self.frame)
        self.labelCategoricalName.setObjectName("labelCategoricalName")
        self.verticalLayout_2.addWidget(self.labelCategoricalName)
        self.listWidgetCategorical = QtWidgets.QListWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetCategorical.sizePolicy().hasHeightForWidth())
        self.listWidgetCategorical.setSizePolicy(sizePolicy)
        self.listWidgetCategorical.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.listWidgetCategorical.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidgetCategorical.setObjectName("listWidgetCategorical")
        self.verticalLayout_2.addWidget(self.listWidgetCategorical)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.listWidgetNumericals = QtWidgets.QListWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.listWidgetNumericals.sizePolicy().hasHeightForWidth())
        self.listWidgetNumericals.setSizePolicy(sizePolicy)
        self.listWidgetNumericals.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.listWidgetNumericals.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listWidgetNumericals.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidgetNumericals.setObjectName("listWidgetNumericals")
        self.verticalLayout_2.addWidget(self.listWidgetNumericals)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBoxTransformations = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxTransformations.setObjectName("comboBoxTransformations")
        self.verticalLayout_4.addWidget(self.comboBoxTransformations)
        self.comboBoxTests = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxTests.setObjectName("comboBoxTests")
        self.verticalLayout_4.addWidget(self.comboBoxTests)
        self.doubleSpinBoxAlpha = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBoxAlpha.setDecimals(3)
        self.doubleSpinBoxAlpha.setMaximum(0.2)
        self.doubleSpinBoxAlpha.setSingleStep(0.001)
        self.doubleSpinBoxAlpha.setProperty("value", 0.05)
        self.doubleSpinBoxAlpha.setObjectName("doubleSpinBoxAlpha")
        self.verticalLayout_4.addWidget(self.doubleSpinBoxAlpha)
        self.checkBoxBonferroni = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxBonferroni.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBoxBonferroni.setObjectName("checkBoxBonferroni")
        self.verticalLayout_4.addWidget(self.checkBoxBonferroni)
        self.gridLayout_6.addLayout(self.verticalLayout_4, 0, 1, 4, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.comboBoxSSMDtype = QtWidgets.QComboBox(self.frame_2)
        self.comboBoxSSMDtype.setObjectName("comboBoxSSMDtype")
        self.horizontalLayout.addWidget(self.comboBoxSSMDtype)
        self.checkBoxDateMatching = QtWidgets.QCheckBox(self.frame_2)
        self.checkBoxDateMatching.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBoxDateMatching.setObjectName("checkBoxDateMatching")
        self.horizontalLayout.addWidget(self.checkBoxDateMatching)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.frame_2)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.framePlotWidget = QtWidgets.QFrame(self.tab)
        self.framePlotWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePlotWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePlotWidget.setObjectName("framePlotWidget")
        self.gridLayout_5.addWidget(self.framePlotWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frameSSMDPlotWidget = QtWidgets.QFrame(self.tab_3)
        self.frameSSMDPlotWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSSMDPlotWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSSMDPlotWidget.setObjectName("frameSSMDPlotWidget")
        self.gridLayout_7.addWidget(self.frameSSMDPlotWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.frameMaskedPlotWidget = QtWidgets.QFrame(self.tab_4)
        self.frameMaskedPlotWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMaskedPlotWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMaskedPlotWidget.setObjectName("frameMaskedPlotWidget")
        self.gridLayout_8.addWidget(self.frameMaskedPlotWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textEditResults = QtWidgets.QTextEdit(self.tab_2)
        self.textEditResults.setObjectName("textEditResults")
        self.gridLayout_4.addWidget(self.textEditResults, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabWidget, 3, 0, 1, 1)
        self.pushButtonRunPairs = QtWidgets.QPushButton(self.frame_2)
        self.pushButtonRunPairs.setObjectName("pushButtonRunPairs")
        self.gridLayout_2.addWidget(self.pushButtonRunPairs, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 0, 1, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "All Columns"))
        self.pushButtonAddCat.setText(_translate("Form", "Add Cat."))
        self.pushButtonAddNum.setText(_translate("Form", "Add Num."))
        self.labelCategoricalName.setText(_translate("Form", "Categorical:"))
        self.listWidgetCategorical.setToolTip(_translate("Form", "<html><head/><body><p>Here is an overview of unique items in your categorical parameters.</p><p><br/></p><p>The selection will be checked against all items. If nothing is selected, all possible pairs will be checked. </p><p><br/></p></body></html>"))
        self.label_2.setText(_translate("Form", "Numericals:"))
        self.groupBox.setTitle(_translate("Form", "Statistics"))
        self.label_4.setText(_translate("Form", "tranformation"))
        self.checkBoxBonferroni.setText(_translate("Form", "Bonferroni Correction"))
        self.label_5.setText(_translate("Form", "test"))
        self.label_6.setText(_translate("Form", "alpha"))
        self.label_7.setText(_translate("Form", "SSMD type:"))
        self.checkBoxDateMatching.setText(_translate("Form", "Attempt date matching for controls"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "pval plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "SSMD plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Masked SSMD plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "p-values"))
        self.pushButtonRunPairs.setText(_translate("Form", "Run Pairs"))

