# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(425, 536)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidgetFolders = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidgetFolders.setObjectName("tabWidgetFolders")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.treeWidgetProjectFolder = QtWidgets.QTreeWidget(self.tab)
        self.treeWidgetProjectFolder.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.treeWidgetProjectFolder.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treeWidgetProjectFolder.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.treeWidgetProjectFolder.setColumnCount(1)
        self.treeWidgetProjectFolder.setObjectName("treeWidgetProjectFolder")
        self.treeWidgetProjectFolder.header().setDefaultSectionSize(100)
        self.gridLayout_2.addWidget(self.treeWidgetProjectFolder, 0, 0, 1, 2)
        self.tabWidgetFolders.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.treeWidgetDataFolder = QtWidgets.QTreeWidget(self.tab_2)
        self.treeWidgetDataFolder.setColumnCount(1)
        self.treeWidgetDataFolder.setObjectName("treeWidgetDataFolder")
        self.treeWidgetDataFolder.header().setDefaultSectionSize(100)
        self.gridLayout.addWidget(self.treeWidgetDataFolder, 0, 0, 1, 1)
        self.tabWidgetFolders.addTab(self.tab_2, "")
        self.gridLayout_3.addWidget(self.tabWidgetFolders, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 425, 21))
        self.menubar.setObjectName("menubar")
        self.menuProject = QtWidgets.QMenu(self.menubar)
        self.menuProject.setObjectName("menuProject")
        self.menuAdd_To_Project = QtWidgets.QMenu(self.menuProject)
        self.menuAdd_To_Project.setObjectName("menuAdd_To_Project")
        self.menuProject_2 = QtWidgets.QMenu(self.menuProject)
        self.menuProject_2.setObjectName("menuProject_2")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuCalculate = QtWidgets.QMenu(self.menuTools)
        self.menuCalculate.setObjectName("menuCalculate")
        self.menuCenterfinding = QtWidgets.QMenu(self.menuTools)
        self.menuCenterfinding.setObjectName("menuCenterfinding")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionScrape_Data = QtWidgets.QAction(MainWindow)
        self.actionScrape_Data.setObjectName("actionScrape_Data")
        self.actionLoad_Pickle = QtWidgets.QAction(MainWindow)
        self.actionLoad_Pickle.setObjectName("actionLoad_Pickle")
        self.actionDetect_Circles = QtWidgets.QAction(MainWindow)
        self.actionDetect_Circles.setObjectName("actionDetect_Circles")
        self.actionAdd_to_Prioject = QtWidgets.QAction(MainWindow)
        self.actionAdd_to_Prioject.setObjectName("actionAdd_to_Prioject")
        self.actionScrape_New_Data = QtWidgets.QAction(MainWindow)
        self.actionScrape_New_Data.setObjectName("actionScrape_New_Data")
        self.actionLoad_Existing_Dataset = QtWidgets.QAction(MainWindow)
        self.actionLoad_Existing_Dataset.setObjectName("actionLoad_Existing_Dataset")
        self.actionCalculate_Common_Metadata = QtWidgets.QAction(MainWindow)
        self.actionCalculate_Common_Metadata.setObjectName("actionCalculate_Common_Metadata")
        self.actionbanana = QtWidgets.QAction(MainWindow)
        self.actionbanana.setObjectName("actionbanana")
        self.actionNew_Project = QtWidgets.QAction(MainWindow)
        self.actionNew_Project.setObjectName("actionNew_Project")
        self.actionLoad_Project = QtWidgets.QAction(MainWindow)
        self.actionLoad_Project.setObjectName("actionLoad_Project")
        self.actionParameters_and_Metadata_for_all = QtWidgets.QAction(MainWindow)
        self.actionParameters_and_Metadata_for_all.setObjectName("actionParameters_and_Metadata_for_all")
        self.actionParameters_for_selection = QtWidgets.QAction(MainWindow)
        self.actionParameters_for_selection.setObjectName("actionParameters_for_selection")
        self.actionOnly_Metadata = QtWidgets.QAction(MainWindow)
        self.actionOnly_Metadata.setObjectName("actionOnly_Metadata")
        self.actionCenterfinding_All = QtWidgets.QAction(MainWindow)
        self.actionCenterfinding_All.setObjectName("actionCenterfinding_All")
        self.actionCenterfinding_selection = QtWidgets.QAction(MainWindow)
        self.actionCenterfinding_selection.setObjectName("actionCenterfinding_selection")
        self.actionMissing_Parameter = QtWidgets.QAction(MainWindow)
        self.actionMissing_Parameter.setObjectName("actionMissing_Parameter")
        self.actionOpen_Data_Explorer = QtWidgets.QAction(MainWindow)
        self.actionOpen_Data_Explorer.setObjectName("actionOpen_Data_Explorer")
        self.menuAdd_To_Project.addAction(self.actionScrape_New_Data)
        self.menuAdd_To_Project.addAction(self.actionLoad_Existing_Dataset)
        self.menuProject_2.addAction(self.actionNew_Project)
        self.menuProject_2.addAction(self.actionLoad_Project)
        self.menuProject.addAction(self.menuProject_2.menuAction())
        self.menuProject.addAction(self.menuAdd_To_Project.menuAction())
        self.menuCalculate.addAction(self.actionParameters_and_Metadata_for_all)
        self.menuCalculate.addAction(self.actionParameters_for_selection)
        self.menuCalculate.addAction(self.actionMissing_Parameter)
        self.menuCalculate.addSeparator()
        self.menuCalculate.addAction(self.actionOnly_Metadata)
        self.menuCenterfinding.addAction(self.actionCenterfinding_All)
        self.menuCenterfinding.addAction(self.actionCenterfinding_selection)
        self.menuTools.addAction(self.menuCenterfinding.menuAction())
        self.menuTools.addAction(self.menuCalculate.menuAction())
        self.menuTools.addAction(self.actionOpen_Data_Explorer)
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidgetFolders.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.treeWidgetProjectFolder.headerItem().setText(0, _translate("MainWindow", "Project Structure"))
        self.tabWidgetFolders.setTabText(self.tabWidgetFolders.indexOf(self.tab), _translate("MainWindow", "Project Data"))
        self.treeWidgetDataFolder.headerItem().setText(0, _translate("MainWindow", "DataFolder Structure"))
        self.tabWidgetFolders.setTabText(self.tabWidgetFolders.indexOf(self.tab_2), _translate("MainWindow", "Raw Data"))
        self.menuProject.setTitle(_translate("MainWindow", "Project"))
        self.menuAdd_To_Project.setTitle(_translate("MainWindow", "Add To Project"))
        self.menuProject_2.setTitle(_translate("MainWindow", "Project..."))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuCalculate.setTitle(_translate("MainWindow", "Calculate..."))
        self.menuCenterfinding.setTitle(_translate("MainWindow", "Centerfinding"))
        self.actionScrape_Data.setText(_translate("MainWindow", "Scrape Data"))
        self.actionLoad_Pickle.setText(_translate("MainWindow", "Load"))
        self.actionDetect_Circles.setText(_translate("MainWindow", "Detect Circles"))
        self.actionAdd_to_Prioject.setText(_translate("MainWindow", "Add to Prioject"))
        self.actionScrape_New_Data.setText(_translate("MainWindow", "Scrape New Data"))
        self.actionLoad_Existing_Dataset.setText(_translate("MainWindow", "Load Existing Dataset"))
        self.actionCalculate_Common_Metadata.setText(_translate("MainWindow", "Calculate only Metadata"))
        self.actionbanana.setText(_translate("MainWindow", "banana"))
        self.actionNew_Project.setText(_translate("MainWindow", "New Project"))
        self.actionLoad_Project.setText(_translate("MainWindow", "Load Project"))
        self.actionParameters_and_Metadata_for_all.setText(_translate("MainWindow", "Parameters for all"))
        self.actionParameters_for_selection.setText(_translate("MainWindow", "Parameters for selection"))
        self.actionOnly_Metadata.setText(_translate("MainWindow", "Only Metadata"))
        self.actionCenterfinding_All.setText(_translate("MainWindow", "Centerfinding All"))
        self.actionCenterfinding_selection.setText(_translate("MainWindow", "Centerfinding Selection"))
        self.actionMissing_Parameter.setText(_translate("MainWindow", "Missing Parameters"))
        self.actionOpen_Data_Explorer.setText(_translate("MainWindow", "Open Data Explorer"))

