# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(425, 536)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidgetFolders = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidgetFolders.setObjectName("tabWidgetFolders")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.treeWidgetProjectFolder = QtWidgets.QTreeWidget(self.tab)
        self.treeWidgetProjectFolder.setColumnCount(1)
        self.treeWidgetProjectFolder.setObjectName("treeWidgetProjectFolder")
        self.treeWidgetProjectFolder.header().setDefaultSectionSize(100)
        self.gridLayout_2.addWidget(self.treeWidgetProjectFolder, 0, 0, 1, 2)
        self.tabWidgetFolders.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.treeWidgetDataFolder = QtWidgets.QTreeWidget(self.tab_2)
        self.treeWidgetDataFolder.setColumnCount(1)
        self.treeWidgetDataFolder.setObjectName("treeWidgetDataFolder")
        self.treeWidgetDataFolder.header().setDefaultSectionSize(100)
        self.gridLayout.addWidget(self.treeWidgetDataFolder, 0, 0, 1, 1)
        self.tabWidgetFolders.addTab(self.tab_2, "")
        self.gridLayout_3.addWidget(self.tabWidgetFolders, 0, 0, 1, 1)
        self.groupBoxProgress = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxProgress.setObjectName("groupBoxProgress")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBoxProgress)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelProgress = QtWidgets.QLabel(self.groupBoxProgress)
        self.labelProgress.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelProgress.setObjectName("labelProgress")
        self.horizontalLayout_2.addWidget(self.labelProgress)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBoxProgress)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.progressBarCPU = QtWidgets.QProgressBar(self.groupBoxProgress)
        self.progressBarCPU.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBarCPU.setProperty("value", 24)
        self.progressBarCPU.setObjectName("progressBarCPU")
        self.horizontalLayout.addWidget(self.progressBarCPU)
        self.gridLayout_4.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBoxProgress, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 425, 21))
        self.menubar.setObjectName("menubar")
        self.menuProject = QtWidgets.QMenu(self.menubar)
        self.menuProject.setObjectName("menuProject")
        self.menuAdd_To_Project = QtWidgets.QMenu(self.menuProject)
        self.menuAdd_To_Project.setObjectName("menuAdd_To_Project")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionScrape_Data = QtWidgets.QAction(MainWindow)
        self.actionScrape_Data.setObjectName("actionScrape_Data")
        self.actionLoad_Pickle = QtWidgets.QAction(MainWindow)
        self.actionLoad_Pickle.setObjectName("actionLoad_Pickle")
        self.actionDetect_Circles = QtWidgets.QAction(MainWindow)
        self.actionDetect_Circles.setObjectName("actionDetect_Circles")
        self.actionAdd_to_Prioject = QtWidgets.QAction(MainWindow)
        self.actionAdd_to_Prioject.setObjectName("actionAdd_to_Prioject")
        self.actionNew_Project = QtWidgets.QAction(MainWindow)
        self.actionNew_Project.setObjectName("actionNew_Project")
        self.actionScrape_New_Data = QtWidgets.QAction(MainWindow)
        self.actionScrape_New_Data.setObjectName("actionScrape_New_Data")
        self.actionLoad_Existing_Dataset = QtWidgets.QAction(MainWindow)
        self.actionLoad_Existing_Dataset.setObjectName("actionLoad_Existing_Dataset")
        self.actionCenterfinding = QtWidgets.QAction(MainWindow)
        self.actionCenterfinding.setEnabled(True)
        self.actionCenterfinding.setObjectName("actionCenterfinding")
        self.actionCalculate_Parameters = QtWidgets.QAction(MainWindow)
        self.actionCalculate_Parameters.setObjectName("actionCalculate_Parameters")
        self.menuAdd_To_Project.addAction(self.actionScrape_New_Data)
        self.menuAdd_To_Project.addAction(self.actionLoad_Existing_Dataset)
        self.menuProject.addAction(self.actionNew_Project)
        self.menuProject.addAction(self.menuAdd_To_Project.menuAction())
        self.menuTools.addAction(self.actionCenterfinding)
        self.menuTools.addAction(self.actionCalculate_Parameters)
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidgetFolders.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.treeWidgetProjectFolder.headerItem().setText(0, _translate("MainWindow", "Project Structure"))
        self.tabWidgetFolders.setTabText(self.tabWidgetFolders.indexOf(self.tab), _translate("MainWindow", "Project Data"))
        self.treeWidgetDataFolder.headerItem().setText(0, _translate("MainWindow", "DataFolder Structure"))
        self.tabWidgetFolders.setTabText(self.tabWidgetFolders.indexOf(self.tab_2), _translate("MainWindow", "Raw Data"))
        self.groupBoxProgress.setTitle(_translate("MainWindow", "GroupBox"))
        self.labelProgress.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "CPU:"))
        self.menuProject.setTitle(_translate("MainWindow", "Project"))
        self.menuAdd_To_Project.setTitle(_translate("MainWindow", "Add To Project"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.actionScrape_Data.setText(_translate("MainWindow", "Scrape Data"))
        self.actionLoad_Pickle.setText(_translate("MainWindow", "Load"))
        self.actionDetect_Circles.setText(_translate("MainWindow", "Detect Circles"))
        self.actionAdd_to_Prioject.setText(_translate("MainWindow", "Add to Prioject"))
        self.actionNew_Project.setText(_translate("MainWindow", "New Project"))
        self.actionScrape_New_Data.setText(_translate("MainWindow", "Scrape New Data"))
        self.actionLoad_Existing_Dataset.setText(_translate("MainWindow", "Load Existing Dataset"))
        self.actionCenterfinding.setText(_translate("MainWindow", "Centerfinding"))
        self.actionCalculate_Parameters.setText(_translate("MainWindow", "Calculate Parameters"))

