# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pandasviewer.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(973, 675)
        Form.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.gridLayout_5 = QtWidgets.QGridLayout(Form)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.AllData = QtWidgets.QWidget()
        self.AllData.setObjectName("AllData")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.AllData)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidgetAllData = QtWidgets.QTableWidget(self.AllData)
        self.tableWidgetAllData.setObjectName("tableWidgetAllData")
        self.tableWidgetAllData.setColumnCount(0)
        self.tableWidgetAllData.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidgetAllData, 0, 0, 1, 1)
        self.tabWidget.addTab(self.AllData, "")
        self.SelectedData = QtWidgets.QWidget()
        self.SelectedData.setObjectName("SelectedData")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.SelectedData)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidgetSelectedData = QtWidgets.QTableWidget(self.SelectedData)
        self.tableWidgetSelectedData.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableWidgetSelectedData.setObjectName("tableWidgetSelectedData")
        self.tableWidgetSelectedData.setColumnCount(0)
        self.tableWidgetSelectedData.setRowCount(0)
        self.gridLayout_3.addWidget(self.tableWidgetSelectedData, 0, 2, 1, 1)
        self.tabWidget.addTab(self.SelectedData, "")
        self.gridLayout_5.addWidget(self.tabWidget, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.AllColumns = QtWidgets.QWidget()
        self.AllColumns.setObjectName("AllColumns")
        self.gridLayout = QtWidgets.QGridLayout(self.AllColumns)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.listWidgetAllColumns = QtWidgets.QListWidget(self.AllColumns)
        self.listWidgetAllColumns.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidgetAllColumns.setObjectName("listWidgetAllColumns")
        self.gridLayout.addWidget(self.listWidgetAllColumns, 0, 0, 1, 1)
        self.pushButtonAddToSelection = QtWidgets.QPushButton(self.AllColumns)
        self.pushButtonAddToSelection.setObjectName("pushButtonAddToSelection")
        self.gridLayout.addWidget(self.pushButtonAddToSelection, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.AllColumns, "")
        self.SelectedColumns = QtWidgets.QWidget()
        self.SelectedColumns.setObjectName("SelectedColumns")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.SelectedColumns)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.listWidgetSelectedColumns = QtWidgets.QListWidget(self.SelectedColumns)
        self.listWidgetSelectedColumns.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidgetSelectedColumns.setObjectName("listWidgetSelectedColumns")
        self.gridLayout_4.addWidget(self.listWidgetSelectedColumns, 0, 0, 1, 1)
        self.pushButtonRemoveFromSelection = QtWidgets.QPushButton(self.SelectedColumns)
        self.pushButtonRemoveFromSelection.setObjectName("pushButtonRemoveFromSelection")
        self.gridLayout_4.addWidget(self.pushButtonRemoveFromSelection, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.SelectedColumns, "")
        self.RowFilters = QtWidgets.QWidget()
        self.RowFilters.setObjectName("RowFilters")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.RowFilters)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBoxSelectedColumns = QtWidgets.QComboBox(self.RowFilters)
        self.comboBoxSelectedColumns.setObjectName("comboBoxSelectedColumns")
        self.verticalLayout.addWidget(self.comboBoxSelectedColumns)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButtonEquals = QtWidgets.QRadioButton(self.RowFilters)
        self.radioButtonEquals.setObjectName("radioButtonEquals")
        self.horizontalLayout.addWidget(self.radioButtonEquals)
        self.lineEditEquals = QtWidgets.QLineEdit(self.RowFilters)
        self.lineEditEquals.setObjectName("lineEditEquals")
        self.horizontalLayout.addWidget(self.lineEditEquals)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButtonStrEquals = QtWidgets.QRadioButton(self.RowFilters)
        self.radioButtonStrEquals.setObjectName("radioButtonStrEquals")
        self.horizontalLayout_2.addWidget(self.radioButtonStrEquals)
        self.lineEditStrEquals = QtWidgets.QLineEdit(self.RowFilters)
        self.lineEditStrEquals.setObjectName("lineEditStrEquals")
        self.horizontalLayout_2.addWidget(self.lineEditStrEquals)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButtonGreaterThan = QtWidgets.QRadioButton(self.RowFilters)
        self.radioButtonGreaterThan.setObjectName("radioButtonGreaterThan")
        self.horizontalLayout_3.addWidget(self.radioButtonGreaterThan)
        self.lineEditGreaterThan = QtWidgets.QLineEdit(self.RowFilters)
        self.lineEditGreaterThan.setObjectName("lineEditGreaterThan")
        self.horizontalLayout_3.addWidget(self.lineEditGreaterThan)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButtonLessThan = QtWidgets.QRadioButton(self.RowFilters)
        self.radioButtonLessThan.setObjectName("radioButtonLessThan")
        self.horizontalLayout_4.addWidget(self.radioButtonLessThan)
        self.lineEditLessThan = QtWidgets.QLineEdit(self.RowFilters)
        self.lineEditLessThan.setObjectName("lineEditLessThan")
        self.horizontalLayout_4.addWidget(self.lineEditLessThan)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButtonIsNot = QtWidgets.QRadioButton(self.RowFilters)
        self.radioButtonIsNot.setObjectName("radioButtonIsNot")
        self.horizontalLayout_5.addWidget(self.radioButtonIsNot)
        self.lineEditIsNot = QtWidgets.QLineEdit(self.RowFilters)
        self.lineEditIsNot.setObjectName("lineEditIsNot")
        self.horizontalLayout_5.addWidget(self.lineEditIsNot)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radioButtonStrIsNot = QtWidgets.QRadioButton(self.RowFilters)
        self.radioButtonStrIsNot.setObjectName("radioButtonStrIsNot")
        self.horizontalLayout_6.addWidget(self.radioButtonStrIsNot)
        self.lineEditStrIsNot = QtWidgets.QLineEdit(self.RowFilters)
        self.lineEditStrIsNot.setObjectName("lineEditStrIsNot")
        self.horizontalLayout_6.addWidget(self.lineEditStrIsNot)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.pushButtonApplyFilters = QtWidgets.QPushButton(self.RowFilters)
        self.pushButtonApplyFilters.setObjectName("pushButtonApplyFilters")
        self.verticalLayout.addWidget(self.pushButtonApplyFilters)
        self.listWidgetAppliedFilters = QtWidgets.QListWidget(self.RowFilters)
        self.listWidgetAppliedFilters.setObjectName("listWidgetAppliedFilters")
        self.verticalLayout.addWidget(self.listWidgetAppliedFilters)
        self.tabWidget_2.addTab(self.RowFilters, "")
        self.gridLayout_6.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AllData), _translate("Form", "All Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SelectedData), _translate("Form", "Selected Data"))
        self.groupBox.setTitle(_translate("Form", "GroupBox"))
        self.pushButtonAddToSelection.setText(_translate("Form", "Add to Selection"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.AllColumns), _translate("Form", "All Columns"))
        self.pushButtonRemoveFromSelection.setText(_translate("Form", "Remove from Selection"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.SelectedColumns), _translate("Form", "Selected Columns"))
        self.radioButtonEquals.setText(_translate("Form", "equals"))
        self.radioButtonStrEquals.setText(_translate("Form", "string equals"))
        self.radioButtonGreaterThan.setText(_translate("Form", "greater than"))
        self.radioButtonLessThan.setText(_translate("Form", "less than"))
        self.radioButtonIsNot.setText(_translate("Form", "is not"))
        self.radioButtonStrIsNot.setText(_translate("Form", "string is not"))
        self.pushButtonApplyFilters.setText(_translate("Form", "Apply"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.RowFilters), _translate("Form", "Row Filters"))

