# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scanner.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(877, 476)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listWidgetAllColumns = QtWidgets.QListWidget(self.frame)
        self.listWidgetAllColumns.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidgetAllColumns.setObjectName("listWidgetAllColumns")
        self.verticalLayout.addWidget(self.listWidgetAllColumns)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonAddCat = QtWidgets.QPushButton(self.frame)
        self.pushButtonAddCat.setObjectName("pushButtonAddCat")
        self.horizontalLayout_2.addWidget(self.pushButtonAddCat)
        self.pushButtonAddNum = QtWidgets.QPushButton(self.frame)
        self.pushButtonAddNum.setObjectName("pushButtonAddNum")
        self.horizontalLayout_2.addWidget(self.pushButtonAddNum)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.listWidgetCategoricals = QtWidgets.QListWidget(self.frame)
        self.listWidgetCategoricals.setObjectName("listWidgetCategoricals")
        self.verticalLayout_2.addWidget(self.listWidgetCategoricals)
        self.pushButtonClearCat = QtWidgets.QPushButton(self.frame)
        self.pushButtonClearCat.setObjectName("pushButtonClearCat")
        self.verticalLayout_2.addWidget(self.pushButtonClearCat)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.listWidgetNumericals = QtWidgets.QListWidget(self.frame)
        self.listWidgetNumericals.setObjectName("listWidgetNumericals")
        self.verticalLayout_3.addWidget(self.listWidgetNumericals)
        self.pushButtonClearNum = QtWidgets.QPushButton(self.frame)
        self.pushButtonClearNum.setObjectName("pushButtonClearNum")
        self.verticalLayout_3.addWidget(self.pushButtonClearNum)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 5, 2)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonFindSignificance = QtWidgets.QPushButton(self.frame_2)
        self.pushButtonFindSignificance.setObjectName("pushButtonFindSignificance")
        self.gridLayout_2.addWidget(self.pushButtonFindSignificance, 1, 0, 1, 2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBoxTransformations = QtWidgets.QComboBox(self.frame_2)
        self.comboBoxTransformations.setObjectName("comboBoxTransformations")
        self.verticalLayout_4.addWidget(self.comboBoxTransformations)
        self.comboBoxTests = QtWidgets.QComboBox(self.frame_2)
        self.comboBoxTests.setObjectName("comboBoxTests")
        self.verticalLayout_4.addWidget(self.comboBoxTests)
        self.doubleSpinBoxAlpha = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBoxAlpha.setMaximum(0.2)
        self.doubleSpinBoxAlpha.setSingleStep(0.01)
        self.doubleSpinBoxAlpha.setProperty("value", 0.05)
        self.doubleSpinBoxAlpha.setObjectName("doubleSpinBoxAlpha")
        self.verticalLayout_4.addWidget(self.doubleSpinBoxAlpha)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 2, 2, 1, 1)
        self.framePlotWidget = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framePlotWidget.sizePolicy().hasHeightForWidth())
        self.framePlotWidget.setSizePolicy(sizePolicy)
        self.framePlotWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePlotWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePlotWidget.setObjectName("framePlotWidget")
        self.gridLayout_3.addWidget(self.framePlotWidget, 3, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "All Columns:"))
        self.pushButtonAddCat.setText(_translate("Form", "Add Cat."))
        self.pushButtonAddNum.setText(_translate("Form", "Add Num."))
        self.label_2.setText(_translate("Form", "Categoricals"))
        self.pushButtonClearCat.setText(_translate("Form", "Clear..."))
        self.label_3.setText(_translate("Form", "Numericals"))
        self.pushButtonClearNum.setText(_translate("Form", "Clear..."))
        self.pushButtonFindSignificance.setText(_translate("Form", "Find Significance"))
        self.label_4.setText(_translate("Form", "tranformation"))
        self.label_5.setText(_translate("Form", "test"))
        self.label_6.setText(_translate("Form", "alpha"))
        self.framePlotWidget.setToolTip(_translate("Form", "<html><head/><body><p>CAUTION! </p><p><br/></p><p>A whole blue frame might mean everything is significant. Check the array outputted to the console. </p><p>This plot is not statistically sound and should just be used as an aid to decided what relationships to explore further.</p><p><br/></p></body></html>"))

