# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'centerfinder_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(742, 569)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBoxCenterFinder = QtWidgets.QGroupBox(Form)
        self.groupBoxCenterFinder.setObjectName("groupBoxCenterFinder")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBoxCenterFinder)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBoxCenterFinder)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBoxminRadius = QtWidgets.QSpinBox(self.groupBoxCenterFinder)
        self.spinBoxminRadius.setMaximum(999)
        self.spinBoxminRadius.setProperty("value", 450)
        self.spinBoxminRadius.setObjectName("spinBoxminRadius")
        self.horizontalLayout.addWidget(self.spinBoxminRadius)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBoxCenterFinder)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBoxmaxRadius = QtWidgets.QSpinBox(self.groupBoxCenterFinder)
        self.spinBoxmaxRadius.setMaximum(999)
        self.spinBoxmaxRadius.setProperty("value", 510)
        self.spinBoxmaxRadius.setObjectName("spinBoxmaxRadius")
        self.horizontalLayout_2.addWidget(self.spinBoxmaxRadius)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBoxCenterFinder)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.spinBoxparam1 = QtWidgets.QSpinBox(self.groupBoxCenterFinder)
        self.spinBoxparam1.setMaximum(999)
        self.spinBoxparam1.setProperty("value", 50)
        self.spinBoxparam1.setObjectName("spinBoxparam1")
        self.horizontalLayout_3.addWidget(self.spinBoxparam1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBoxCenterFinder)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.spinBoxparam2 = QtWidgets.QSpinBox(self.groupBoxCenterFinder)
        self.spinBoxparam2.setMaximum(999)
        self.spinBoxparam2.setProperty("value", 20)
        self.spinBoxparam2.setObjectName("spinBoxparam2")
        self.horizontalLayout_4.addWidget(self.spinBoxparam2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBoxCenterFinder)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.spinBoxThreshold = QtWidgets.QSpinBox(self.groupBoxCenterFinder)
        self.spinBoxThreshold.setMaximum(255)
        self.spinBoxThreshold.setProperty("value", 150)
        self.spinBoxThreshold.setObjectName("spinBoxThreshold")
        self.horizontalLayout_5.addWidget(self.spinBoxThreshold)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.comboBoxThresholdMethod = QtWidgets.QComboBox(self.groupBoxCenterFinder)
        self.comboBoxThresholdMethod.setEditable(False)
        self.comboBoxThresholdMethod.setCurrentText("")
        self.comboBoxThresholdMethod.setObjectName("comboBoxThresholdMethod")
        self.horizontalLayout_6.addWidget(self.comboBoxThresholdMethod)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.pushButtonRedoCenter = QtWidgets.QPushButton(self.groupBoxCenterFinder)
        self.pushButtonRedoCenter.setObjectName("pushButtonRedoCenter")
        self.verticalLayout.addWidget(self.pushButtonRedoCenter)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.gridLayout.addWidget(self.groupBoxCenterFinder, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.listWidgetVideos = QtWidgets.QListWidget(self.groupBox_2)
        self.listWidgetVideos.setObjectName("listWidgetVideos")
        self.gridLayout_3.addWidget(self.listWidgetVideos, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 4, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonStartStop = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonStartStop.setCheckable(True)
        self.pushButtonStartStop.setObjectName("pushButtonStartStop")
        self.gridLayout_2.addWidget(self.pushButtonStartStop, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)

        self.retranslateUi(Form)
        self.comboBoxThresholdMethod.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBoxCenterFinder.setTitle(_translate("Form", "CenterFinder Settings"))
        self.label.setText(_translate("Form", "min Radius"))
        self.label_2.setText(_translate("Form", "max Radius"))
        self.label_3.setText(_translate("Form", "Param1"))
        self.label_4.setText(_translate("Form", "Param2"))
        self.label_5.setText(_translate("Form", "Threshold"))
        self.pushButtonRedoCenter.setText(_translate("Form", "Redo"))
        self.groupBox_2.setTitle(_translate("Form", "Loaded Videos"))
        self.groupBox.setTitle(_translate("Form", "Automatic"))
        self.pushButtonStartStop.setText(_translate("Form", "Start"))

